### PR TITLE
WIP - Documentation and basic read functionality

### PR DESCRIPTION
**Pull request by nzlosh**
The PowerDNS pypi repository is out of date so the new active github repository is used in the requirements.txt file until the author published the module.

Documentation is generated using pack2md.

Basic read access for servers and zone lists.

### CODE REVIEW

**Comment by kvedder-amplex** [comment]
Hi @nzlosh,
I am working on some changes to this pack as well. Would you be willing to coordinate to split the work? Seems like you've taken the same path that I started down. Maybe I could work on the functionality for records?  It'd also be great to get whatever is working into an approved PR.

Ken

**Comment by nzlosh** [comment]
Hi @kvedder-amplex,

If you'd like to work on the records part, that would be great.  You can get a copy of the unmerged changes from my repo if you want so that we're working off the same base.

https://github.com/nzlosh/stackstorm-powerdns

The idea is to have the core code in `/lib/base.py` with the `action_xxxx.py` being thin wrappers around the base.  Record updates can be a bit tricky with the PowerDNS API because you need to make sure the record hasn't changed between the time you read from it and the time you write to it.  This is especially important when the Resource Record Set has multiple entries like the TXT records can.

**Comment by kvedder-amplex** [comment]
So the functionality I intended was to basically use the pack to facilitate a one way sync between our Netbox IPAM. What the records are currently aren't that big of a deal, as the data from the IPAM should be the source of truth. With that said, most of the entries made using ST2 should be A records for devices. What was your use case for the pack?

Also, perhaps we could get some of the code working and approved to make the collaboration a bit cleaner? Not sure what the approval process is for packs yet.

**Comment by nzlosh** [comment]
The pack is intended to be a generic, low level implementation for accessing PowerDNS REST API features.

With such pack I plan on creating a custom pack that contains business logic to allow external teams to create, update and delete DNS entries through action-alias like
`!st2 pdns create myhost A 127.0.0.1 zone example.com`.

I was debating adding an action that would read a file to populate an entire zone.  It's similar to the idea of you Netbox/IPAM sync.  It would allow users to write code to dump out their zones from whatever database technology they have into the supported format to be imported by StackStorm.

I'd like keep Netbox and other technologies out of the PowerDNS pack to keep development simple and focused on the core product.

**Comment by kvedder-amplex** [comment]
Agreed, I have your code in my system now with the git repo for
python-powerdns. I will see what I can do and get another PR in within the
next 24 hours.

**Pull request merged**
